# isOk workflow basico - sumar un npm version patch
name: Run Build & Test

on:
  push:
    branches:
      - develop

jobs:
  test:
    name: Running Units Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
      - name: "Automated Version Bump"
        uses: "phips28/gh-action-bump-version@master"
        env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version-type: "patch"
